export const DONORS: string[] = [
  "Mario Rossi", "Giulia Bianchi", "Marco Verdi", "Sofia Neri", "Alessandro Russo", 
  "Chiara Romano", "Francesco Gallo", "Elisa Conti", "Leonardo De Luca", "Beatrice Costa", 
  "Lorenzo Giordano", "Viola Mancini", "Riccardo Moretti", "Alice Barone", "Tommaso Rizzo", 
  "Anna Ferrara", "Federico Martini", "Martina Greco", "Gabriele Marino", "Emma D'Amico", 
  "Simone Esposito", "Greta Lombardi", "Davide Bruno", "Caterina Ferri", "Edoardo Villa", 
  "Giorgia Palmieri", "Andrea Ricci", "Matilde Leone", "Giovanni Fontana", "Isabella Santoro",
  "Luca Colombo", "Elena Greco", "Antonio Ferretti", "Valentina Barbieri", "Giovanni Morelli",
  "Sara Pellegrini", "Pietro Rinaldi", "Francesca Bellini", "Daniele Marchetti", "Caterina Mariani",
  "Matteo Santoro", "Alessia Valentini", "Filippo Bernardi", "Eleonora Gatti", "Samuele Ferraro",
  "Laura Basso", "Christian D'Angelo", "Giorgia Silvestri", "Nicholas Serra", "Vittoria Longo",
  "Mattia Fabbri", "Ludovica Galli", "Stefano Coppola", "Noemi Ruggiero", "Giuseppe Rossetti",
  "Nicole Mariani", "Vincenzo Amato", "Arianna Vitale", "Salvatore Marchetti", "Aurora Testa",
  "Angelo Battaglia", "Camilla Pellegrino", "Diego Grasso", "Irene Fiore", "Raffaele Carbone",
  "Sveva De Angelis", "Michele Farina", "Angelica Orlando", "Paolo Marini", "Ginevra Pugliese",
  "Roberto D'Agostino", "Carlotta Basile", "Claudio Caputo", "Vanessa Sanna", "Fabio Conte",
  "Serena Ferrara", "Massimo Morelli", "Rebecca Lo Presti", "Domenico Franco", "Cristina Riva",
  "Valerio Bernini", "Giada Serra", "Alberto Genovese", "Lucrezia Gagliardi", "Emanuele Vitagliano",
  "Laura Mazza", "Jacopo Lombardi", "Sara Montanari", "Gianmarco De Rosa", "Alessandra Ferretti",
  "Filippo Cattaneo", "Eleonora Belli", "Samuele Martini", "Bianca Furlan", "Christian Vitale",
  "Anna Rinaldi", "Davide Santini", "Sofia Leoni", "Marco Piras", "Martina Cozzi",
  "Lorenzo Palumbo", "Giulia Guerra", "Riccardo Testa", "Chiara Oldani", "Tommaso Sala",
  "Alice Negri", "Federico Grassi", "Noemi Vitali", "Gabriele Ferrari", "Emma Bianchi",
  "Simone Rossi", "Greta Verdi", "Edoardo Neri", "Giorgia Russo", "Andrea Romano",
  "Matilde Gallo", "Giovanni Conti", "Isabella De Luca", "Luca Costa", "Elena Giordano",
  "Antonio Mancini", "Valentina Moretti", "Pietro Barone", "Francesca Rizzo", "Daniele Ferrara"
];